DEFINE=commands.DefineCommand
PUSH=commands.PushCommand
POP=commands.PopCommand
PRINT=commands.PrintCommand
SQRT=commands.SqrtCommand
SUB=commands.SubtractCommand
ADD=commands.AddCommand
DIV=commands.DivisionCommand
MUL=commands.MultiplicationCommand
EXIT=commands.ExitCommand
//=commands.CommentCommand
